### ISSUE TITLE
pullup declaration

### ISSUE THREAD

**Issue by DROID8622** [MCUdude/MicroCore#117]
Thank you for your work!
I have a suggestion - If I want to use analogRead with PULLUP , I need to write PB4 for setup  `pinMode(PB4, INPUT_PULLUP);` and then A2 for analogRead  `Serial.println(analogRead(A2));` , if I write  `pinMode(A2, INPUT_PULLUP);` - pullup resistor does not work for me. Should it be fixed?

**Comment by MCUdude** [comment]
There is no good solution to solve this. Since the Actual pin numbers and the analog pin numbers doesn't match, there is a tradeoff.

As you can see, A0..A3 is really just defined to 0..3. This means that you can't use A0..A3 when using pinMode because you will be referring to the wrong pin.

https://github.com/MCUdude/MicroCore/blob/4fe0ca082af8423906a15b1f3d48aefb54e494d9/avr/variants/attiny13/pins_arduino.h#L72-L75

The solution is to enable pullups using pinMode, but by using the actual pin number (for instance, PB4).
