### ISSUE TITLE
Suggestion: Add "Preserve EEPROM through erase" menu

### ISSUE THREAD

**Issue by bratoff** [MCUdude/MicroCore#71]
The released core always programs "preserve eeprom", which is not always desirable.  Please see attached boards.txt for a suggested way to make this another menu option:

[boards.txt](https://github.com/MCUdude/MicroCore/files/2622863/boards.txt)

Note - this boards.txt also modifies the BOD and LTO menu texts so they display more meaningfully on the status line.

**Comment by maxint-rd** [comment]
I'm not sure why my ATtiny13A didn't preserve EEPROM contents, but when I found out that the EEPROM was erased every time I flashed it, I quickly found this post. I tested it and it worked great for me.

Now I can make sketches that use the EEPROM without losing its contents after programming the MCU.
(Badly needed as I'm currently working on an I2C-peripheral that allows the I2C address to be changed and stored to survive resets).

+1 in support of incorporating this option in the otherwise fabulous MicroCore.

**Comment by MCUdude** [comment]
It was added in d6e6c71, but I haven't done a new release yet. If you need it right now, you can do a manual install

**Comment by maxint-rd** [comment]
Hi @MCUdude , Thank you. I've already done that.

Thanks btw for providing your cores. I'm happily enjoying them in my experiments with various Atmel chips. Great work!

P.S. Setting fuses by using the option "burn boatloader" probably also would have helped me, but that's an afterthought...
